#!/bin/sh

set -eo pipefail

tar --exclude .terraform -C /workspace -xf -
terraform remote config -backend=s3 -backend-config="region=$STATE_REGION" -backend-config="bucket=$STATE_BUCKET" -backend-config="key=$STATE_KEY" -backend-config="encrypt=true"
terraform get
exec terraform "$@"
