#!/bin/sh

set -eo pipefail

tar --exclude .terraform -C /workspace -xf -
terraform init -backend-config="region=$STATE_REGION" -backend-config="bucket=$STATE_BUCKET" -backend-config="key=$STATE_KEY" -backend-config="encrypt=true"
exec terraform "$@"
